name: Build app

on:
  workflow_call:
    inputs:
      do-win:
        type: boolean
        default: true
      do-lin:
        type: boolean
        default: true
      app-ver:
        type: string
        default: "dev"
      upload-tag:
        type: string
        default: "dev"
      upload-artifact:
        type: boolean
        default: true

jobs:

  build-for-lib:
    uses: ./.github/workflows/build-lib.yml

  build-for-win:
    if: ${{ inputs.do-win }}
    needs: [build-for-lib]
    name: build-for-windows
    runs-on: ubuntu-latest

    steps:
      - run: |
          mkdir -p ./build
          mkdir -p ./target

      - name: Checkuot source
        uses: actions/checkout@v4

      - name: Cache build artifacts
        uses: actions/cache@v3
        with:
          key:  app-win-artifacts-${{ hashFiles('**/lockfiles') }}
          path: |
            ./build

      - name: Download build-lib-artifact
        uses: actions/download-artifact@v4
        with:
          name: build-lib-artifact

      - name: Build win
        run: |
          rsync -acv --delete --delete-excluded --exclude='lib/' --exclude='lin/' ./src/ ./build/
          mkdir -p ./target/win
          tar --exclude='*.tar' -c -f ./target/win/win.tar ./build/*
          zip ./target/app-win-${{ inputs.app-ver }}.zip ./target/lib/lib.tar ./target/win/win.tar

      - name: Publish artifacts
        if: ${{ inputs.upload-artifact }}
        uses: softprops/action-gh-release@v1
        with:
          # name: app ${{ inputs.app-ver }}
          tag_name: ${{ inputs.upload-tag }}
          target_commitish: ${{ github.sha }}
          # draft: true
          prerelease: true
          files: |
            ./target/app-win-${{ inputs.app-ver }}.zip

  build-for-lin:
    if: ${{ inputs.do-lin }}
    needs: [build-for-lib]
    name: build-for-linux
    runs-on: ubuntu-latest

    steps:
      - run: |
          mkdir -p ./build
          mkdir -p ./target

      - name: Checkuot source
        uses: actions/checkout@v4

      - name: Cache build artifacts
        uses: actions/cache@v3
        with:
          key:  app-lin-artifacts-${{ hashFiles('**/lockfiles') }}
          path: |
            ./build

      - name: Download build-lib-artifact
        uses: actions/download-artifact@v4
        with:
          name: build-lib-artifact

      - name: Build lin
        run: |
          rsync -acv --delete --delete-excluded --exclude='lib/' --exclude='win/' ./src/ ./build/
          mkdir -p ./target/lin
          tar --exclude='*.tar' -c -f ./target/lin/lin.tar ./build/*
          zip ./target/app-lin-${{ inputs.app-ver }}.zip ./target/lib/lib.tar ./target/lin/lin.tar

      - name: Publish artifacts
        if: ${{ inputs.upload-artifact }}
        uses: softprops/action-gh-release@v1
        with:
          # name: app ${{ inputs.app-ver }}
          tag_name: ${{ inputs.upload-tag }}
          target_commitish: ${{ github.sha }}
          # draft: true
          prerelease: true
          files: |
            ./target/app-lin-*.zip