name: Build application

on:
  workflow_dispatch:
    inputs:
      do-win:
        type: boolean
        default: true
        required: true
      do-lin:
        type: boolean
        default: true
        required: true
      app-ver:
        type: string
        default: "dev"
        required: true
      upload-tag:
        type: string
        default: "dev"
        required: true
      upload-artifact:
        type: boolean
        default: true
        required: true

jobs:
    run-build-app:
        uses: ./.github/workflows/build-app.yml
        secrets: inherit